[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api/Dockerfile"
watchPatterns = [
  "apps/api/**",
  "packages/**",
  "pnpm-lock.yaml",
  "package.json",
  "pnpm-workspace.yaml"
]

[deploy]
preDeployCommand = ["node /app/node_modules/prisma/build/index.js migrate deploy --schema /app/packages/database/prisma/schema.prisma"]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
